### ISSUE TITLE
jar is not compatible with dse 6.0.1 and dse 6.0.2 

### ISSUE THREAD

**Issue by dkjha811** [yabinmeng/tombstone_counter#2]
jar is not compatible with dse 6.0.1 and dse 6.0.2, Can you please fix and provide a new jar. 

While executing with dse 6.0.2 we are getting below error message 

Processing SSTable data files under directory: /var/lib/cassandra/data/mcd_crds/cust_xtnd_prof_data-9e1765b29c8f11e8a93f937f9e64c891
Exception in thread "main" java.lang.IllegalArgumentException: No Type constant bti
        at org.apache.cassandra.io.sstable.format.SSTableFormat$Type.validate(SSTableFormat.java:81)
        at org.apache.cassandra.io.sstable.Descriptor.fromFilename(Descriptor.java:270)
        at org.apache.cassandra.io.sstable.Descriptor.fromFilename(Descriptor.java:223)
        at org.apache.cassandra.io.sstable.Descriptor.fromFilename(Descriptor.java:212)
        at com.castools.TombStoneCounter.main(TombStoneCounter.java:153)

**Comment by dkjha811** [comment]
Paras from Datastax also got the same issue

**Comment by yabinmeng** [comment]
This utility uses open source software (OSS) C* library to handle SSTable scanning. DSE 6.0 has a new SSTable format that is not recognized by OSS C* library.

Supporting DSE 6.0 won't be fixed in this public repo because it may involve DataStax proprietary code. My public repos only cover OSS related codes.
